[project]
name = "rs-diffusion"
version = "0.1.0"
description = "Diffusion methods for remote sensing content generation"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
    "torch==2.5.1",
    "torchvision==0.20.1",
]
